version: "3.8"
services:
#  web:
#    image: nginx
#    ports:
#      - 80:80
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
#    depends_on:
#      - application
  mysql:
    container_name: mysql-8.0.30
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=voca-api
      - MYSQL_USER=local
      - MYSQL_PASSWORD=localpassword
      - MYSQL_ROOT_PASSWORD=vanille
      - TZ=Asia/Seoul
    networks:
      - voca
  application:
    build:
      context: .
    ports:
      - 8088:8088
    container_name: voca-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/voca-api?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: local
      SPRING_DATASOURCE_PASSWORD: localpassword
      spring.profiles.active: local
    depends_on:
      - mysql
    networks:
      - voca

networks:
  voca: