version: "3.8"
services:
  mysql:
    container_name: mysql-8.0.30
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=voca-api
      - MYSQL_USER=local
      - MYSQL_PASSWORD=localpassword
      - MYSQL_ROOT_PASSWORD=vanille
      - TZ=Asia/Seoul