spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voca-api?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: local
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size:  100
        format_sql: true

server.port: 8088
