spring:
  datasource:
    url: jdbc:mysql://localhost:3306/voca-api?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
    username: local
    password: localpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: voca.service@gmail.com
    password: bdsuiipzgeqykywe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000


  jpa:
#    defer-datasource-initialization: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size:  100
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

jwt:
  secret-key: voca-backend-secretkey-application-yml-local
  token.expired-time-ms: 2592000000   # 30 days

server.port: 8088
front-server: http://localhost:8089

management:
  endpoints:
    web:
      exposure:
        include=health,metrics:
google:
  client-id: 178996359638-7l7a0t9l4slvtdvao0amrtf7tg47mphh.apps.googleusercontent.com
  client-secret: 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
  scope:
    - email
    - profile
---

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/voca-api-test?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8
#    username: root
#    password: vanille
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  sql:
#    init:
#      mode: always
#
#  jpa:
#    defer-datasource-initialization: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate.ddl-auto: create-drop
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#        format_sql: true




